# Generated by Django 6.0.4 on 2026-05-13 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Titre (EN)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Description (FR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('category', models.CharField(choices=[('event', 'Événementiel'), ('coaching', 'Coaching'), ('shooting', 'Shooting'), ('caravan', 'Caravane'), ('other', 'Autre')], max_length=20)),
                ('cover_image', models.ImageField(upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Titre (EN)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Description (FR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('icon', models.CharField(blank=True, help_text="Emoji ou nom d'icône", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True, verbose_name='Bio (EN)')),
                ('photo', models.ImageField(upload_to='talents/')),
                ('instagram', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Talent',
                'verbose_name_plural': 'Talents',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200, verbose_name='Rôle (FR)')),
                ('role_en', models.CharField(blank=True, max_length=200, verbose_name='Rôle (EN)')),
                ('bio', models.TextField(blank=True, verbose_name='Bio (FR)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Bio (EN)')),
                ('photo', models.ImageField(upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(verbose_name='Témoignage (FR)')),
                ('content_en', models.TextField(blank=True, verbose_name='Témoignage (EN)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-rating', 'author'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.service', verbose_name='Service demandé')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('client_phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('description', models.TextField(verbose_name='Description du besoin')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('consulting', 'Consultation en cours'), ('planning', 'Planification'), ('execution', 'Exécution'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la phase')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'À faire'), ('in_progress', 'En cours'), ('paid', 'Payée'), ('completed', 'Terminée')], default='pending', max_length=20, verbose_name='Statut')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('phase_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.serviceorder', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Phase de commande',
                'verbose_name_plural': 'Phases de commande',
                'ordering': ['phase_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la phase')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix indicatif (FCFA)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='api.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Phase standard',
                'verbose_name_plural': 'Phases standard',
                'ordering': ['order'],
            },
        ),
    ]
