# Generated by Django 6.0.4 on 2026-05-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='talents/')),
                ('instagram', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Talent',
                'verbose_name_plural': 'Talents',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='team/')),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['author'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('event', 'Événementiel'), ('coaching', 'Coaching'), ('shooting', 'Shooting'), ('caravan', 'Caravane'), ('other', 'Autre')], default='other', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(default='other', upload_to='projects/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
