# Generated by Django 6.0.4 on 2026-05-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type de talent',
                'verbose_name_plural': 'Types de talents',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='talent',
            name='types',
            field=models.ManyToManyField(blank=True, to='api.talenttype', verbose_name='Types de talent'),
        ),
    ]
